### ISSUE TITLE
IndexError: list index out of range (right after cloned)

### ISSUE THREAD

**Issue by santiagodemierre** [elsonjose/FaceSmasher#1]
(base) santiago@santiago-Aspire-A515-51:~/Remember-Me$ python getbdays.py
Traceback (most recent call last):
  File "getbdays.py", line 89, in <module>
    getbirthdays(os.path.abspath(sys.argv[1]))
IndexError: list index out of range

With python3

(base) santiago@santiago-Aspire-A515-51:~/Remember-Me$ python getbdays.py
Traceback (most recent call last):
  File "getbdays.py", line 89, in <module>
    getbirthdays(os.path.abspath(sys.argv[1]))
IndexError: list index out of range

solved by doing driver = driver.Chrome() and getbirthdays() instead of passing getbirthdays(os.path.abspath(sys.argv[1]))

**Comment by elsonjose** [comment]
The script require path for chrome driver as the first system argument. I guess the readme is vague... I'll update it soon with the solution. 
Thanks for taking your time.
